complex.o: complex.c
	gcc -Wall -Werror -c complex.c -o complex.o

solve.o: solve.c
	gcc -Wall -Werror -c solve.c -o solve.o

my_prog.o: my_prog.c
	gcc -Wall -Werror -c my_prog.c -o my_prog.o

my_prog.x: complex.o solve.o my_prog.o
	gcc -o my_prog.x complex.o solve.o my_prog.o -lm
