all: my_prog.x

my_prog.x: complex.o solve.o my_prog.o
	gcc -o my_prog.x complex.o solve.o my_prog.o -lm

complex.o: complex.c
	gcc -Wall -Werror -c complex.c -o complex.o

solve.o: solve.c
	gcc -Wall -Werror -c solve.c -o solve.o

my_prog.o: my_prog.c
	gcc -Wall -Werror -c my_prog.c -o my_prog.o

clean:
	rm -f my_prog.o complex.o solve.o

realclean: clean
	rm -f my_prog.x
